module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        ft: {
          bg: '#06080e',
          bgPanel: '#0a0e18',
          grass: '#5a8a3a',
          grassTopHi: '#7ab050',
          grassTopDk: '#3a5a20',
          grassTopAccent: '#9ad068',
          grassSideL: '#2a4a18',
          grassSideR: '#142a0a',
          stone: '#8c94a0',
          stoneTopHi: '#b0b8c0',
          stoneTopDk: '#5a626c',
          stoneTopAccent: '#d0d8e0',
          stoneSideL: '#4a525c',
          stoneSideR: '#2a3038',
          path: '#a08868',
          pathTopHi: '#c0a888',
          pathTopDk: '#705840',
          pathTopAccent: '#d8b890',
          pathSideL: '#604830',
          pathSideR: '#382818',
          water: '#3a78a8',
          waterTopHi: '#5a98c8',
          waterTopDk: '#1a4878',
          waterTopAccent: '#8ab8e0',
          waterSideL: '#1a3858',
          waterSideR: '#0a2040',
          panelOuter: '#3a2010',
          panelBorderDk: '#5a3018',
          panelBorderMd: '#8a5c2a',
          panelTop: '#fbf3da',
          panelMid: '#f0e3c0',
          panelBot: '#e2cf99',
          panelInnerHi: '#fff9e4',
          panelInnerHi2: '#c8a868',
          panelHeader: '#e8d9b0',
          panelHover: '#f7eccd',
          panelFg: '#2a1a08',
          panelFgSoft: '#5a3a1c',
          panelDim: '#8a6e4a',
          panelAccent: '#8a3018',
          panelAccentDp: '#5a1808',
          gold: '#c89030',
          goldDk: '#8a5e1c',
          goldHi: '#e8b860',
          accent: '#d4b574',
          accentHi: '#e8d4a0',
          accentDeep: '#8a6e3a',
          fg: '#f0ede4',
          fgSoft: '#c8c4b8',
          fgPlain: '#e8e6df',
          fgPlainSoft: '#a8b0bd',
          dim: '#6a7088',
          dimPlain: '#6b7280',
          line: '#1d232e',
          hpGreen: '#5fa83a',
          mpBlue: '#3a78c8',
          ctYellow: '#c89030',
        },
      },
      fontFamily: {
        jetbrains: ['"JetBrains Mono"', 'ui-monospace', 'Menlo', 'monospace'],
        pixel: ['"Press Start 2P"', 'monospace'],
        cinzel: ['"Cinzel"', '"Cormorant Garamond"', 'Georgia', 'serif'],
        body: ['"Cormorant Garamond"', 'Georgia', 'serif'],
      },
    },
  },
  plugins: [],
};
